# Generated by Django 5.1.6 on 2025-11-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='编程语言名称')),
            ],
            options={
                'verbose_name': 'CodingLanguage',
                'verbose_name_plural': 'CodingLanguage',
            },
        ),
        migrations.CreateModel(
            name='LoadBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('competitor', models.CharField(default='unknown', max_length=500, verbose_name='审计员名称')),
                ('payouts', models.CharField(default='0', max_length=500, verbose_name='获取的总收益')),
                ('total_findings', models.CharField(default='0', max_length=500, verbose_name='找到的总问题数')),
                ('solo', models.CharField(default='0', max_length=500, verbose_name='个人找到的问题')),
                ('high', models.CharField(default='0', max_length=500, verbose_name='找到的高危漏洞数量')),
                ('med', models.CharField(default='0', max_length=500, verbose_name='找到的中危漏洞数量')),
                ('solo_high', models.CharField(default='0', max_length=500, verbose_name='个人找到的高危漏洞数量')),
                ('solo_med', models.CharField(default='0', max_length=500, verbose_name='个人找到的中危漏洞数量')),
                ('first_place', models.CharField(default='0', max_length=500, verbose_name='第一位置发现数量')),
            ],
            options={
                'verbose_name': 'LeadBoard',
                'verbose_name_plural': 'LeadBoard',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='类别名称')),
            ],
            options={
                'verbose_name': 'ProjectType',
                'verbose_name_plural': 'ProjectType',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.CharField(default='', max_length=200, verbose_name='钱包地址')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='网络名称')),
                ('sub_name', models.CharField(default='unknown', max_length=500, verbose_name='子名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='network/%Y/%m/%d/')),
                ('detail', models.CharField(default='unknown', max_length=500, verbose_name='网络详细')),
                ('coding_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_language_network', to='solid.codinglanguage', verbose_name='项目编程')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type_network', to='solid.projecttype', verbose_name='项目类别')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Network',
            },
        ),
        migrations.CreateModel(
            name='AuditProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='审计项目的名称')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='audit/%Y/%m/%d/')),
                ('start_time', models.CharField(default='', max_length=100, verbose_name='审计开始时间')),
                ('end_time', models.CharField(default='', max_length=100, verbose_name='审计结束时间')),
                ('cycle', models.CharField(default='', max_length=100, verbose_name='审计周期')),
                ('status', models.CharField(choices=[('Prepare', 'Prepare'), ('Ongoing', 'Ongoing'), ('End', 'End')], default='Ongoing', max_length=100, verbose_name='项目状态')),
                ('detail', models.CharField(default='unknown', max_length=500, verbose_name='项目描述')),
                ('bounty_fund', models.CharField(default='unknown', max_length=500, verbose_name='项目赏金')),
                ('project_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='项目链接')),
                ('report_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='项目链接')),
                ('x_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='X链接')),
                ('telegram', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Telegram')),
                ('discord', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Discord 链接')),
                ('github', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Github 链接')),
                ('community_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Github 链接')),
                ('bounty_description', models.CharField(default='unknown', max_length=500, verbose_name='奖励描述')),
                ('coding_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_language_relation', to='solid.codinglanguage', verbose_name='项目编程')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_language_relation', to='solid.network', verbose_name='项目编程')),
                ('project_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_type_relation', to='solid.projecttype', verbose_name='项目类别')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_relation', to='solid.user', verbose_name='项目所属用户')),
            ],
            options={
                'verbose_name': 'AuditProject',
                'verbose_name_plural': 'AuditProject',
            },
        ),
        migrations.CreateModel(
            name='ProjectPeopleComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='Social', max_length=100, verbose_name='成员姓名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member/%Y/%m/%d/')),
                ('position', models.CharField(default='unknown', max_length=500, verbose_name='成员职位')),
                ('detail', models.CharField(default='unknown', max_length=500, verbose_name='成员评论')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_audit_relation', to='solid.auditproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'ProjectPeopleComments',
                'verbose_name_plural': 'ProjectPeopleComments',
            },
        ),
    ]
