# Generated by Django 5.1.6 on 2025-09-16 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='Social', max_length=100, verbose_name='成员姓名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member/%Y/%m/%d/')),
                ('detail', models.CharField(default='unknown', max_length=500, verbose_name='成员简介')),
            ],
            options={
                'verbose_name': 'CoreMember',
                'verbose_name_plural': 'CoreMember',
            },
        ),
        migrations.CreateModel(
            name='LoadBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('competitor', models.CharField(default='unknown', max_length=500, verbose_name='审计员名称')),
                ('payouts', models.CharField(default='0', max_length=500, verbose_name='获取的总收益')),
                ('total_findings', models.CharField(default='0', max_length=500, verbose_name='找到的总问题数')),
                ('solo', models.CharField(default='0', max_length=500, verbose_name='个人找到的问题')),
                ('high', models.CharField(default='0', max_length=500, verbose_name='找到的高危漏洞数量')),
                ('med', models.CharField(default='0', max_length=500, verbose_name='找到的中危漏洞数量')),
                ('solo_high', models.CharField(default='0', max_length=500, verbose_name='个人找到的高危漏洞数量')),
                ('solo_med', models.CharField(default='0', max_length=500, verbose_name='个人找到的中危漏洞数量')),
                ('first_place', models.CharField(default='0', max_length=500, verbose_name='第一位置发现数量')),
            ],
            options={
                'verbose_name': 'LeadBoard',
                'verbose_name_plural': 'LeadBoard',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='服务名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/%Y/%m/%d/')),
                ('detail', models.CharField(default='unknown', max_length=500, verbose_name='服务描述')),
            ],
            options={
                'verbose_name': 'ServiceType',
                'verbose_name_plural': 'ServiceType',
            },
        ),
        migrations.CreateModel(
            name='AuditProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='审计项目的名称')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='audit/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Prepare', 'Prepare'), ('Ongoing', 'Ongoing'), ('End', 'End')], default='Ongoing', max_length=100, verbose_name='项目状体')),
                ('project_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='项目链接')),
                ('detail', models.CharField(default='unknown', max_length=500, verbose_name='项目描述')),
                ('report_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='项目链接')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_type', to='solid.servicetype', verbose_name='项目类别')),
            ],
            options={
                'verbose_name': 'AuditProject',
                'verbose_name_plural': 'AuditProject',
            },
        ),
    ]
