# Generated by Django 5.1.6 on 2025-11-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askaudit',
            old_name='images',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='auditproject',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='network',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='projectpeoplecomments',
            name='photo',
        ),
        migrations.AddField(
            model_name='auditproject',
            name='photo_url',
            field=models.CharField(default='', max_length=200, verbose_name='图片地址'),
        ),
        migrations.AddField(
            model_name='network',
            name='icon_url',
            field=models.CharField(default='', max_length=200, verbose_name='icon地址'),
        ),
        migrations.AddField(
            model_name='projectpeoplecomments',
            name='photo_url',
            field=models.CharField(default='Social', max_length=200, verbose_name='图片路径'),
        ),
    ]
