# Generated by Django 5.1.6 on 2025-11-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0002_rename_images_askaudit_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditproject',
            name='community_link',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='社区链接'),
        ),
        migrations.AlterField(
            model_name='auditproject',
            name='report_link',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='审计报告链接'),
        ),
    ]
