# Generated by Django 4.1.1 on 2024-03-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirdropUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='unknown', max_length=100, verbose_name='用户名')),
                ('invite_code', models.CharField(default='0000-0000-0000', max_length=100, unique=True, verbose_name='邀请码')),
                ('invite_me_uuid', models.CharField(default='0000-0000-0000', max_length=100, verbose_name='邀请人')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='symbol/%Y/%m/%d/')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='用户地址')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('points', models.PositiveIntegerField(default=0, verbose_name='积分数量')),
                ('x_twitter', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='x')),
                ('discord', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='discord')),
                ('telegram', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='discord')),
                ('info', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人介绍')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.CharField(max_length=100, verbose_name='用户地址')),
                ('type', models.CharField(choices=[('Invite', 'Invite'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking')], default='BridgeTransfer', max_length=100, verbose_name='交易类别')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='积分数量')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airdrop_user', to='airdrop.airdropuser', verbose_name='收藏的商家')),
            ],
            options={
                'verbose_name': 'PointsRecord',
                'verbose_name_plural': 'PointsRecord',
            },
        ),
    ]
