# Generated by Django 5.1.6 on 2025-09-16 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirdropUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='unknown', max_length=100, verbose_name='用户名')),
                ('invite_code', models.CharField(default='0000-0000-0000', max_length=100, unique=True, verbose_name='邀请码')),
                ('invite_me_uuid', models.CharField(default='0000-0000-0000', max_length=100, verbose_name='邀请人')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='symbol/%Y/%m/%d/')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='用户地址')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('points', models.PositiveIntegerField(default=0, verbose_name='积分数量')),
                ('x_twitter', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='x')),
                ('discord', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='discord')),
                ('telegram', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='discord')),
                ('info', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人介绍')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='', max_length=200, verbose_name='活动主题')),
                ('sub_title', models.CharField(default='', max_length=200, verbose_name='活动副标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='period/%Y/%m/%d/', verbose_name='活动图片')),
                ('link_url', models.CharField(default='', max_length=100, verbose_name='活动链接')),
                ('period', models.CharField(blank=True, max_length=300, verbose_name='活动周期')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Period',
            },
        ),
        migrations.CreateModel(
            name='PeriodReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('amount', models.CharField(max_length=100, verbose_name='中奖金额')),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PeriodReward',
                'verbose_name_plural': 'PeriodReward',
            },
        ),
        migrations.CreateModel(
            name='ProjectInterAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('step', models.CharField(blank=True, max_length=100, verbose_name='交互步骤')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/', verbose_name='交互Icon')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='交互名称')),
                ('describe', models.CharField(max_length=200, verbose_name='交互描述')),
                ('link_url', models.CharField(blank=True, max_length=200, verbose_name='交互链接')),
                ('language', models.CharField(choices=[('zh', 'zh'), ('en', 'en')], default='en', max_length=100, verbose_name='语言')),
                ('points_type', models.CharField(choices=[('Invite', 'Invite'), ('Social', 'Social'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking'), ('BridgeWithdraw', 'BridgeWithdraw'), ('bridgeGrants', 'bridgeGrants'), ('Layer3Staking', 'Layer3Staking'), ('Layer3Unstaking', 'Layer3Unstaking'), ('Layer3Withdraw', 'Layer3Withdraw'), ('Layer3Grants', 'Layer3Grants'), ('LayerAppChainInterAction', 'LayerAppChainInterAction'), ('SubmitProject', 'SubmitProject')], default='BridgeTransfer', max_length=100, verbose_name='积分类型')),
                ('project_type', models.CharField(choices=[('Social', 'Social'), ('Project', 'Project')], default='Project', max_length=100, verbose_name='项目类型')),
                ('once_points', models.PositiveIntegerField(default=0, verbose_name='每次交互获得的积分数量')),
                ('daily_max_points', models.PositiveIntegerField(default=0, verbose_name='每天交互的最大积分数')),
                ('max_points', models.PositiveIntegerField(default=0, verbose_name='最大积分数')),
            ],
            options={
                'verbose_name': 'ProjectInterAction',
                'verbose_name_plural': 'ProjectInterAction',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('question', models.CharField(max_length=200, unique=True, verbose_name='问题名称')),
                ('answer', models.CharField(max_length=500, unique=True, verbose_name='问题答案')),
                ('language', models.CharField(choices=[('zh', 'zh'), ('en', 'en')], default='en', max_length=100, verbose_name='语言')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='PointsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('Invite', 'Invite'), ('Social', 'Social'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking'), ('BridgeWithdraw', 'BridgeWithdraw'), ('bridgeGrants', 'bridgeGrants'), ('Layer3Staking', 'Layer3Staking'), ('Layer3Unstaking', 'Layer3Unstaking'), ('Layer3Withdraw', 'Layer3Withdraw'), ('Layer3Grants', 'Layer3Grants'), ('LayerAppChainInterAction', 'LayerAppChainInterAction'), ('SubmitProject', 'SubmitProject')], default='BridgeTransfer', max_length=100, verbose_name='积分类型')),
                ('address', models.CharField(max_length=100, verbose_name='用户地址')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='积分数量')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airdrop_user', to='airdrop.airdropuser', verbose_name='收藏的商家')),
            ],
            options={
                'verbose_name': 'PointsRecord',
                'verbose_name_plural': 'PointsRecord',
            },
        ),
    ]
