# Generated by Django 4.1.1 on 2024-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinteraction',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d/', verbose_name='交互Icon'),
        ),
        migrations.AddField(
            model_name='projectinteraction',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='交互链接'),
        ),
        migrations.AddField(
            model_name='projectinteraction',
            name='step',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='交互步骤'),
        ),
        migrations.AlterField(
            model_name='projectinteraction',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='交互名称'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=500, unique=True, verbose_name='问题答案'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=200, unique=True, verbose_name='问题名称'),
        ),
    ]
