# Generated by Django 4.1.1 on 2024-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0002_projectinteraction_icon_projectinteraction_link_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinteraction',
            old_name='type',
            new_name='project_type',
        ),
        migrations.AddField(
            model_name='projectinteraction',
            name='daily_max_points',
            field=models.PositiveIntegerField(default=0, verbose_name='每天交互的最大积分数'),
        ),
        migrations.AddField(
            model_name='projectinteraction',
            name='once_points',
            field=models.PositiveIntegerField(default=0, verbose_name='每次交互获得的积分数量'),
        ),
        migrations.AddField(
            model_name='projectinteraction',
            name='points_type',
            field=models.CharField(choices=[('Invite', 'Invite'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking'), ('BridgeWithdraw', 'BridgeWithdraw'), ('bridgeGrants', 'bridgeGrants')], default='BridgeTransfer', max_length=100, unique=True, verbose_name='积分类型'),
        ),
        migrations.AlterField(
            model_name='pointsrecord',
            name='type',
            field=models.CharField(choices=[('Invite', 'Invite'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking'), ('BridgeWithdraw', 'BridgeWithdraw'), ('bridgeGrants', 'bridgeGrants')], default='BridgeTransfer', max_length=100, verbose_name='积分类型'),
        ),
    ]
