# Generated by Django 4.1.1 on 2024-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0003_rename_type_projectinteraction_project_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, verbose_name='中奖期数')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('amount', models.CharField(max_length=100, verbose_name='中奖金额')),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PeriodReward',
                'verbose_name_plural': 'PeriodReward',
            },
        ),
    ]
