# Generated by Django 4.1.1 on 2024-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0004_periodreward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodreward',
            name='name',
        ),
        migrations.AddField(
            model_name='periodreward',
            name='period',
            field=models.CharField(blank=True, max_length=300, verbose_name='活动周期'),
        ),
        migrations.AddField(
            model_name='periodreward',
            name='sub_title',
            field=models.CharField(default='', max_length=200, verbose_name='活动副标题'),
        ),
        migrations.AddField(
            model_name='periodreward',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='活动主题'),
        ),
    ]
