# Generated by Django 4.1.1 on 2024-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0006_period_remove_periodreward_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinteraction',
            name='describe',
            field=models.CharField(max_length=200, verbose_name='交互描述'),
        ),
        migrations.AlterField(
            model_name='projectinteraction',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='交互名称'),
        ),
        migrations.AlterField(
            model_name='projectinteraction',
            name='points_type',
            field=models.CharField(choices=[('Invite', 'Invite'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking'), ('BridgeWithdraw', 'BridgeWithdraw'), ('bridgeGrants', 'bridgeGrants')], default='BridgeTransfer', max_length=100, verbose_name='积分类型'),
        ),
        migrations.AlterField(
            model_name='projectinteraction',
            name='step',
            field=models.CharField(blank=True, max_length=100, verbose_name='交互步骤'),
        ),
    ]
