# Generated by Django 4.1.1 on 2024-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0007_alter_projectinteraction_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointsrecord',
            name='type',
            field=models.CharField(choices=[('Invite', 'Invite'), ('Social', 'Social'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking'), ('BridgeWithdraw', 'BridgeWithdraw'), ('bridgeGrants', 'bridgeGrants'), ('Layer3Staking', 'Layer3Staking'), ('Layer3Unstaking', 'Layer3Unstaking'), ('Layer3Withdraw', 'Layer3Withdraw'), ('Layer3Grants', 'Layer3Grants'), ('LayerAppChainInterAction', 'LayerAppChainInterAction'), ('SubmitProject', 'SubmitProject')], default='BridgeTransfer', max_length=100, verbose_name='积分类型'),
        ),
        migrations.AlterField(
            model_name='projectinteraction',
            name='points_type',
            field=models.CharField(choices=[('Invite', 'Invite'), ('Social', 'Social'), ('BridgeTransfer', 'BridgeTransfer'), ('BridgeStaking', 'BridgeStaking'), ('BridgeWithdraw', 'BridgeWithdraw'), ('bridgeGrants', 'bridgeGrants'), ('Layer3Staking', 'Layer3Staking'), ('Layer3Unstaking', 'Layer3Unstaking'), ('Layer3Withdraw', 'Layer3Withdraw'), ('Layer3Grants', 'Layer3Grants'), ('LayerAppChainInterAction', 'LayerAppChainInterAction'), ('SubmitProject', 'SubmitProject')], default='BridgeTransfer', max_length=100, verbose_name='积分类型'),
        ),
    ]
