# Generated by Django 4.1.1 on 2024-03-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='unknown', max_length=200, verbose_name='博客标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/')),
                ('describe', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='描述')),
                ('link_url', models.CharField(default='', max_length=100, verbose_name='博客链接')),
                ('tags', models.CharField(default='', max_length=200, verbose_name='标签')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='unknown', max_length=100, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': 'BlogCat',
                'verbose_name_plural': 'BlogCat',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='事件名称')),
                ('link_url', models.CharField(default='', max_length=100, verbose_name='事件链接')),
                ('describe', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='事件描述')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('link_url', models.CharField(default='', max_length=100, verbose_name='form 链接')),
                ('describe', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forum',
            },
        ),
    ]
