# Generated by Django 4.1.1 on 2024-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blog_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/%Y/%m/%d/'),
        ),
    ]
