# Generated by Django 4.1.1 on 2022-10-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=128, verbose_name='wallet ID')),
                ('wallet_head', models.CharField(max_length=256, verbose_name='wallet wallethead')),
                ('head_public_key', models.TextField(verbose_name='generate public key')),
                ('head_private_key', models.TextField(verbose_name='generate private key')),
                ('head_ipfs_addr', models.CharField(max_length=128, verbose_name='ipfs address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Head Storage',
                'verbose_name_plural': 'Head Storage',
            },
        ),
        migrations.AddConstraint(
            model_name='storage',
            constraint=models.UniqueConstraint(fields=('wallet_id', 'wallet_head'), name='uniq_wallet_head_id'),
        ),
    ]
