# Generated by Django 4.1.1 on 2022-11-15 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiAuth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(default="", max_length=64, verbose_name="接入名称"),
                ),
                (
                    "api_token",
                    models.CharField(
                        default="unknown", max_length=128, verbose_name="接入 api Token"
                    ),
                ),
                (
                    "is_expire",
                    models.CharField(
                        choices=[("yes", "yes"), ("no", "no")],
                        default="no",
                        max_length=128,
                        verbose_name="Token是否过期",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UnVerify", "UnVerify"),
                            ("Verifing", "Verifing"),
                            ("Verified", "Verified"),
                        ],
                        default="checking",
                        max_length=32,
                        verbose_name="API 审核状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 授权表",
                "verbose_name_plural": "API 授权表",
            },
        ),
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(db_index=True, max_length=70, verbose_name="链名称"),
                ),
                ("mark", models.CharField(max_length=70, verbose_name="链名标识")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="wallet/%Y/%m/%d/"
                    ),
                ),
                (
                    "active_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="wallet/%Y/%m/%d/"
                    ),
                ),
            ],
            options={
                "verbose_name": "链表",
                "verbose_name_plural": "链表",
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(db_index=True, max_length=70, verbose_name="资产名称"),
                ),
                ("mark", models.CharField(max_length=70, verbose_name="资产标识")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="wallet/%Y/%m/%d/"
                    ),
                ),
                (
                    "active_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="wallet/%Y/%m/%d/"
                    ),
                ),
                (
                    "unit",
                    models.CharField(db_index=True, max_length=10, verbose_name="资产精度"),
                ),
                (
                    "chain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.chain",
                        verbose_name="链名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产表",
                "verbose_name_plural": "资产表",
            },
        ),
    ]
