# Generated by Django 2.2.3 on 2022-10-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=70, verbose_name='链名称')),
                ('mark', models.CharField(max_length=70, verbose_name='链名标识')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='wallet/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': '链表',
                'verbose_name_plural': '链表',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=70, verbose_name='链名称')),
                ('mark', models.CharField(max_length=70, verbose_name='链名标识')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='wallet/%Y/%m/%d/')),
                ('unit', models.CharField(db_index=True, max_length=10, verbose_name='资产精度')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Chain', verbose_name='链名称')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
            },
        ),
    ]
