# Generated by Django 2.2.3 on 2022-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_asset_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='mark',
            field=models.CharField(max_length=70, verbose_name='资产标识'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(db_index=True, max_length=70, verbose_name='资产名称'),
        ),
    ]
