# Generated by Django 5.1.6 on 2025-09-16 03:30

import common.model_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='交易所名称')),
                ('config', models.TextField(blank=True, verbose_name='配置信息')),
                ('market_type', models.CharField(choices=[('Cex', 'Cex'), ('Dex', 'Dex')], default='Cex', max_length=100, verbose_name='交易所类别')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Down', 'Down')], default='Active', max_length=100, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchange',
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sell_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('buy_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('usd_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('cny_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('avg_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('margin', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('base_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_relate_asset', to='common.asset')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_exchange', to='market.exchange')),
                ('qoute_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qoute_relate_asset', to='common.asset')),
            ],
            options={
                'verbose_name': 'MarketPrice',
                'verbose_name_plural': 'MarketPrice',
            },
        ),
        migrations.CreateModel(
            name='FavoriteMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(max_length=70, verbose_name='设备ID')),
                ('market_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_market_price', to='market.marketprice')),
            ],
            options={
                'verbose_name': 'FavoriteMarket',
                'verbose_name_plural': 'FavoriteMarket',
            },
        ),
        migrations.CreateModel(
            name='StablePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('usd_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('cny_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otc_asset', to='common.asset')),
            ],
            options={
                'verbose_name': 'StablePrice',
                'verbose_name_plural': 'StablePrice',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='交易对名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='symbol/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Down', 'Down')], default='Active', max_length=100, verbose_name='状态')),
                ('category', models.CharField(choices=[('Spot', 'Spot'), ('Future', 'Future'), ('Option', 'Option')], default='Spot', max_length=100)),
                ('base_asset', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_symbols', to='common.asset', verbose_name='base资产')),
                ('quote_asset', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_symbols', to='common.asset', verbose_name='报价资产')),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbol',
            },
        ),
        migrations.AddField(
            model_name='marketprice',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_symbol', to='market.symbol'),
        ),
    ]
