# Generated by Django 2.2.3 on 2022-10-01 03:24

import common.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0002_address_wallet_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='交易所名称')),
                ('config', models.TextField(blank=True, verbose_name='配置信息')),
                ('market_type', models.CharField(choices=[('Cex', 'Cex'), ('Dex', 'Dex')], default='Cex', max_length=100, verbose_name='交易所类别')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Down', 'Down')], default='Active', max_length=100, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchange',
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='交易对名称')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Down', 'Down')], default='Active', max_length=100, verbose_name='状态')),
                ('category', models.CharField(choices=[('Spot', 'Spot'), ('Future', 'Future'), ('Option', 'Option')], default='Spot', max_length=100)),
                ('base_asset', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_symbols', to='wallet.Asset', verbose_name='base资产')),
                ('quote_asset', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_symbols', to='wallet.Asset', verbose_name='报价资产')),
            ],
            options={
                'verbose_name': 'Symbol',
                'verbose_name_plural': 'Symbol',
            },
        ),
        migrations.CreateModel(
            name='StablePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('usd_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('cny_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otc_asset', to='wallet.Asset')),
            ],
            options={
                'verbose_name': 'StablePrice',
                'verbose_name_plural': 'StablePrice',
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sell_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('buy_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('usd_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('cny_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('avg_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('margin', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('base_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_asset', to='wallet.Asset')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_exchange', to='market.Exchange')),
                ('qoute_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qoute_asset', to='wallet.Asset')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_symbol', to='market.Symbol')),
            ],
            options={
                'verbose_name': 'MarketPrice',
                'verbose_name_plural': 'MarketPrice',
            },
        ),
    ]
