# Generated by Django 2.2.3 on 2022-10-01 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(max_length=70, verbose_name='设备ID')),
                ('market_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='symbol_market_price', to='market.MarketPrice')),
            ],
            options={
                'verbose_name': 'FavoriteMarket',
                'verbose_name_plural': 'FavoriteMarket',
            },
        ),
    ]
