# Generated by Django 3.2.18 on 2023-03-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketprice',
            name='base_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_relate_asset', to='common.asset'),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='qoute_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qoute_relate_asset', to='common.asset'),
        ),
    ]
