# Generated by Django 2.2.3 on 2022-10-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_favoritemarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketprice',
            name='base_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_asset', to='common.Asset'),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='qoute_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qoute_asset', to='common.Asset'),
        ),
        migrations.AlterField(
            model_name='stableprice',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otc_asset', to='common.Asset'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='base_asset',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_symbols', to='common.Asset', verbose_name='base资产'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='quote_asset',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_symbols', to='common.Asset', verbose_name='报价资产'),
        ),
    ]
