# Generated by Django 2.2.3 on 2022-09-02 15:29

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=70, verbose_name='链名称')),
                ('mark', models.CharField(max_length=70, verbose_name='链名标识')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='wallet/%Y/%m/%d/')),
                ('unit', models.CharField(db_index=True, max_length=10, verbose_name='资产精度')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=70, verbose_name='链名称')),
                ('mark', models.CharField(max_length=70, verbose_name='链名标识')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='wallet/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': '链表',
                'verbose_name_plural': '链表',
            },
        ),
        migrations.CreateModel(
            name='TxRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('from_addr', models.CharField(max_length=70, verbose_name='发送方')),
                ('to_addr', models.CharField(max_length=70, verbose_name='接收方')),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='转账金额')),
                ('memo', models.CharField(max_length=70, verbose_name='备注')),
                ('hash', models.CharField(max_length=70, verbose_name='交易Hash')),
                ('block_height', models.CharField(max_length=70, verbose_name='所在区块')),
                ('tx_time', models.CharField(max_length=70, verbose_name='交易时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Asset', verbose_name='资产名称')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Chain', verbose_name='链名称')),
            ],
            options={
                'verbose_name': '交易记录表',
                'verbose_name_plural': '交易记录表',
            },
        ),
        migrations.CreateModel(
            name='TokenConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('token_name', models.CharField(max_length=70, verbose_name='token 名称')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='wallet/%Y/%m/%d/')),
                ('token_symbol', models.CharField(max_length=70, verbose_name='Token符号')),
                ('contract_addr', models.CharField(max_length=70, verbose_name='合约地址')),
                ('decimal', models.CharField(db_index=True, max_length=10, verbose_name='token 精度')),
                ('is_hot', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=32, verbose_name='是不是热门资产')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Asset', verbose_name='资产名称')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Chain', verbose_name='链名称')),
            ],
            options={
                'verbose_name': '资产配置表',
                'verbose_name_plural': '资产配置表',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Chain', verbose_name='链名称'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('network', models.CharField(choices=[('mainnet', 'mainnet'), ('testnet', 'testnet')], default='mainnet', max_length=32, verbose_name='主网测试网')),
                ('device_id', models.CharField(max_length=70, verbose_name='设备ID')),
                ('wallet_name', models.CharField(max_length=70, verbose_name='钱包名称')),
                ('address', models.CharField(max_length=70, verbose_name='钱包地址')),
                ('contract_addr', models.CharField(max_length=70, verbose_name='合约地址')),
                ('balance', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='钱包余额')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Asset', verbose_name='资产名称')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Chain', verbose_name='链名称')),
            ],
            options={
                'verbose_name': '地址表',
                'verbose_name_plural': '地址表',
            },
        ),
        migrations.CreateModel(
            name='AddresNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(max_length=70, verbose_name='设备ID')),
                ('memo', models.CharField(max_length=70, verbose_name='地址备注')),
                ('address', models.CharField(max_length=70, verbose_name='地址')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Asset', verbose_name='资产名称')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Chain', verbose_name='链名称')),
            ],
            options={
                'verbose_name': '地址薄表',
                'verbose_name_plural': '地址薄表',
            },
        ),
    ]
