# Generated by Django 5.1.6 on 2025-09-16 03:30

import common.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('index', models.CharField(db_index=True, max_length=10, verbose_name='address index')),
                ('address', models.CharField(max_length=70, verbose_name='address')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
            },
        ),
        migrations.CreateModel(
            name='AddresNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(max_length=70, verbose_name='device id')),
                ('memo', models.CharField(max_length=70, verbose_name='memo')),
                ('address', models.CharField(max_length=70, verbose_name='address')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.asset', verbose_name='asset name')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.chain', verbose_name='chain name')),
            ],
            options={
                'verbose_name': 'AddresNote',
                'verbose_name_plural': 'AddresNote',
            },
        ),
        migrations.CreateModel(
            name='AddressAmountStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='amount')),
                ('timedate', models.CharField(max_length=70, verbose_name='timedate')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'AddressAmountStat',
                'verbose_name_plural': 'AddressAmountStat',
            },
        ),
        migrations.CreateModel(
            name='TokenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('token_name', models.CharField(max_length=70, verbose_name='token name')),
                ('token_symbol', models.CharField(max_length=70, verbose_name='Token symbol')),
                ('contract_addr', models.CharField(max_length=70, verbose_name='contract address')),
                ('decimal', models.CharField(db_index=True, max_length=10, verbose_name='token decimal')),
                ('is_hot', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=32, verbose_name='is_hot asset')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.asset', verbose_name='asset name')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.chain', verbose_name='chain name')),
            ],
            options={
                'verbose_name': 'TokenConfig',
                'verbose_name_plural': 'TokenConfig',
            },
        ),
        migrations.CreateModel(
            name='TxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('from_addr', models.CharField(max_length=70, verbose_name='sender')),
                ('to_addr', models.CharField(max_length=70, verbose_name='reviver')),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='amount')),
                ('memo', models.CharField(max_length=70, verbose_name='memo')),
                ('hash', models.CharField(max_length=70, verbose_name='hash')),
                ('block_height', models.CharField(max_length=70, verbose_name='block_height')),
                ('tx_time', models.CharField(max_length=70, verbose_name='tx_time')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.asset', verbose_name='asset name')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.chain', verbose_name='chain name')),
            ],
            options={
                'verbose_name': 'TxRecord',
                'verbose_name_plural': 'TxRecord',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_id', models.CharField(max_length=70, verbose_name='device id')),
                ('wallet_uuid', models.CharField(max_length=70, verbose_name='wallet uuid')),
                ('wallet_name', models.CharField(max_length=70, verbose_name='wallet name')),
                ('asset_usd', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='total usd')),
                ('asset_cny', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='total cny')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_chain', to='common.chain', verbose_name='chain')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='AddressAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('asset_usd', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='address usd')),
                ('asset_cny', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='address cny')),
                ('balance', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='address balance')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_asset_address', to='wallet.address', verbose_name='address')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_asset_asset', to='common.asset', verbose_name='asset')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_asset_wallet', to='wallet.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'AddressAsset',
                'verbose_name_plural': 'AddressAsset',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_address', to='wallet.wallet', verbose_name='wallet'),
        ),
        migrations.CreateModel(
            name='WalletAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('contract_addr', models.CharField(max_length=70, verbose_name='contract address')),
                ('asset_usd', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='wallet usd')),
                ('asset_cny', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='wallet cny')),
                ('balance', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='wallet balance')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_asset_asset', to='common.asset', verbose_name='asset')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_asset_wallet', to='wallet.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'WalletAsset',
                'verbose_name_plural': 'WalletAsset',
            },
        ),
        migrations.CreateModel(
            name='WalletHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('wallet_head', models.CharField(max_length=512, verbose_name='wallethead')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'WalletHead',
                'verbose_name_plural': 'WalletHead',
            },
        ),
    ]
