# Generated by Django 2.2.3 on 2022-09-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='wallet_uuid',
            field=models.CharField(default=1, max_length=70, verbose_name='wallet_uuid'),
            preserve_default=False,
        ),
    ]
