# Generated by Django 4.1.1 on 2022-11-20 12:07

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addresnote",
            options={"verbose_name": "AddresNote", "verbose_name_plural": "AddresNote"},
        ),
        migrations.AlterModelOptions(
            name="tokenconfig",
            options={
                "verbose_name": "TokenConfig",
                "verbose_name_plural": "TokenConfig",
            },
        ),
        migrations.AlterModelOptions(
            name="txrecord",
            options={"verbose_name": "TxRecord", "verbose_name_plural": "TxRecord"},
        ),
        migrations.AlterModelOptions(
            name="walletasset",
            options={
                "verbose_name": "WalletAsset",
                "verbose_name_plural": "WalletAsset",
            },
        ),
        migrations.RemoveField(
            model_name="tokenconfig",
            name="icon",
        ),
        migrations.AlterField(
            model_name="addresnote",
            name="address",
            field=models.CharField(max_length=70, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="addresnote",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.asset",
                verbose_name="asset name",
            ),
        ),
        migrations.AlterField(
            model_name="addresnote",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.chain",
                verbose_name="chain name",
            ),
        ),
        migrations.AlterField(
            model_name="addresnote",
            name="device_id",
            field=models.CharField(max_length=70, verbose_name="device id"),
        ),
        migrations.AlterField(
            model_name="addresnote",
            name="memo",
            field=models.CharField(max_length=70, verbose_name="memo"),
        ),
        migrations.AlterField(
            model_name="tokenconfig",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.asset",
                verbose_name="asset name",
            ),
        ),
        migrations.AlterField(
            model_name="tokenconfig",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.chain",
                verbose_name="chain name",
            ),
        ),
        migrations.AlterField(
            model_name="tokenconfig",
            name="contract_addr",
            field=models.CharField(max_length=70, verbose_name="contract address"),
        ),
        migrations.AlterField(
            model_name="tokenconfig",
            name="decimal",
            field=models.CharField(
                db_index=True, max_length=10, verbose_name="token decimal"
            ),
        ),
        migrations.AlterField(
            model_name="tokenconfig",
            name="is_hot",
            field=models.CharField(
                choices=[("yes", "yes"), ("no", "no")],
                default="no",
                max_length=32,
                verbose_name="is_hot asset",
            ),
        ),
        migrations.AlterField(
            model_name="tokenconfig",
            name="token_name",
            field=models.CharField(max_length=70, verbose_name="token name"),
        ),
        migrations.AlterField(
            model_name="tokenconfig",
            name="token_symbol",
            field=models.CharField(max_length=70, verbose_name="Token symbol"),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="amount",
            field=common.models.DecField(
                decimal_places=30,
                default=Decimal("0E-18"),
                max_digits=65,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.asset",
                verbose_name="asset name",
            ),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="block_height",
            field=models.CharField(max_length=70, verbose_name="block_height"),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="chain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.chain",
                verbose_name="chain name",
            ),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="from_addr",
            field=models.CharField(max_length=70, verbose_name="sender"),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="hash",
            field=models.CharField(max_length=70, verbose_name="hash"),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="memo",
            field=models.CharField(max_length=70, verbose_name="memo"),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="to_addr",
            field=models.CharField(max_length=70, verbose_name="reviver"),
        ),
        migrations.AlterField(
            model_name="txrecord",
            name="tx_time",
            field=models.CharField(max_length=70, verbose_name="tx_time"),
        ),
    ]
