# Generated by Django 2.2.3 on 2022-10-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20221003_1120'),
        ('wallet', '0002_address_wallet_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresnote',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Asset', verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='addresnote',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Chain', verbose_name='链名称'),
        ),
        migrations.AlterField(
            model_name='address',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Asset', verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='address',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Chain', verbose_name='链名称'),
        ),
        migrations.AlterField(
            model_name='tokenconfig',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Asset', verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='tokenconfig',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Chain', verbose_name='链名称'),
        ),
        migrations.AlterField(
            model_name='txrecord',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Asset', verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='txrecord',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Chain', verbose_name='链名称'),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
    ]
