# Generated by Django 3.2.18 on 2023-03-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_addresnote_options_alter_tokenconfig_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallethead',
            name='ipfs_cid',
        ),
        migrations.RemoveField(
            model_name='wallethead',
            name='rsa_private_key',
        ),
        migrations.RemoveField(
            model_name='wallethead',
            name='rsa_public_key',
        ),
    ]
