# Generated by Django 2.2.3 on 2022-10-03 11:01

import common.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20221003_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAmountStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', common.models.DecField(decimal_places=30, default=Decimal('0E-18'), max_digits=65, verbose_name='amount')),
                ('timedate', models.CharField(max_length=70, verbose_name='timedate')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Address', verbose_name='address')),
            ],
            options={
                'verbose_name': 'AddressAmountStat',
                'verbose_name_plural': 'AddressAmountStat',
            },
        ),
    ]
