# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: savourrpc/airdrop.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from services.savour_rpc import common_pb2 as savourrpc_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='savourrpc/airdrop.proto',
  package='savourrpc.airdrop',
  syntax='proto3',
  serialized_options=b'\n\024group.savour.airdropZ\017./proto/airdrop',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17savourrpc/airdrop.proto\x12\x11savourrpc.airdrop\x1a\x16savourrpc/common.proto\"I\n\x10\x44ppLinkPointsReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"D\n\x10\x44ppLinkPointsRep\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.savourrpc.ReturnCode\x12\x0b\n\x03msg\x18\x02 \x01(\t2s\n\x0e\x41irdropService\x12\x61\n\x13submitDppLinkPoints\x12#.savourrpc.airdrop.DppLinkPointsReq\x1a#.savourrpc.airdrop.DppLinkPointsRep\"\x00\x42\'\n\x14group.savour.airdropZ\x0f./proto/airdropb\x06proto3'
  ,
  dependencies=[savourrpc_dot_common__pb2.DESCRIPTOR,])




_DPPLINKPOINTSREQ = _descriptor.Descriptor(
  name='DppLinkPointsReq',
  full_name='savourrpc.airdrop.DppLinkPointsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='savourrpc.airdrop.DppLinkPointsReq.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='savourrpc.airdrop.DppLinkPointsReq.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='savourrpc.airdrop.DppLinkPointsReq.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=143,
)


_DPPLINKPOINTSREP = _descriptor.Descriptor(
  name='DppLinkPointsRep',
  full_name='savourrpc.airdrop.DppLinkPointsRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='savourrpc.airdrop.DppLinkPointsRep.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='savourrpc.airdrop.DppLinkPointsRep.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=213,
)

_DPPLINKPOINTSREP.fields_by_name['code'].enum_type = savourrpc_dot_common__pb2._RETURNCODE
DESCRIPTOR.message_types_by_name['DppLinkPointsReq'] = _DPPLINKPOINTSREQ
DESCRIPTOR.message_types_by_name['DppLinkPointsRep'] = _DPPLINKPOINTSREP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DppLinkPointsReq = _reflection.GeneratedProtocolMessageType('DppLinkPointsReq', (_message.Message,), {
  'DESCRIPTOR' : _DPPLINKPOINTSREQ,
  '__module__' : 'savourrpc.airdrop_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.airdrop.DppLinkPointsReq)
  })
_sym_db.RegisterMessage(DppLinkPointsReq)

DppLinkPointsRep = _reflection.GeneratedProtocolMessageType('DppLinkPointsRep', (_message.Message,), {
  'DESCRIPTOR' : _DPPLINKPOINTSREP,
  '__module__' : 'savourrpc.airdrop_pb2'
  # @@protoc_insertion_point(class_scope:savourrpc.airdrop.DppLinkPointsRep)
  })
_sym_db.RegisterMessage(DppLinkPointsRep)


DESCRIPTOR._options = None

_AIRDROPSERVICE = _descriptor.ServiceDescriptor(
  name='AirdropService',
  full_name='savourrpc.airdrop.AirdropService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=215,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='submitDppLinkPoints',
    full_name='savourrpc.airdrop.AirdropService.submitDppLinkPoints',
    index=0,
    containing_service=None,
    input_type=_DPPLINKPOINTSREQ,
    output_type=_DPPLINKPOINTSREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRDROPSERVICE)

DESCRIPTOR.services_by_name['AirdropService'] = _AIRDROPSERVICE

# @@protoc_insertion_point(module_scope)
