# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: savour_rpc/appchain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='savour_rpc/appchain.proto',
  package='services.savour_rpc.appchain',
  syntax='proto3',
  serialized_options=b'\n\025group.savour.appchainZ\020./proto/appchain',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19savour_rpc/appchain.proto\x12\x1cservices.savour_rpc.appchain\"\\\n\x1cL1StakerRewardsAmountRequest\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\t\x12\x16\n\x0estaker_address\x18\x02 \x01(\t\x12\x12\n\nstrategies\x18\x03 \x01(\t\"Q\n\x1dL1StakerRewardsAmountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06income\x18\x03 \x01(\t\"Z\n\x1cL2StakerRewardsAmountRequest\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\t\x12\x16\n\x0estaker_address\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\"Q\n\x1dL2StakerRewardsAmountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06income\x18\x03 \x01(\t2\xb7\x02\n\x0f\x41ppChainService\x12\x90\x01\n\x15L1StakerRewardsAmount\x12:.services.savour_rpc.appchain.L1StakerRewardsAmountRequest\x1a;.services.savour_rpc.appchain.L1StakerRewardsAmountResponse\x12\x90\x01\n\x15L2StakerRewardsAmount\x12:.services.savour_rpc.appchain.L2StakerRewardsAmountRequest\x1a;.services.savour_rpc.appchain.L2StakerRewardsAmountResponseB)\n\x15group.savour.appchainZ\x10./proto/appchainb\x06proto3'
)




_L1STAKERREWARDSAMOUNTREQUEST = _descriptor.Descriptor(
  name='L1StakerRewardsAmountRequest',
  full_name='services.savour_rpc.appchain.L1StakerRewardsAmountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='services.savour_rpc.appchain.L1StakerRewardsAmountRequest.chain_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='staker_address', full_name='services.savour_rpc.appchain.L1StakerRewardsAmountRequest.staker_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strategies', full_name='services.savour_rpc.appchain.L1StakerRewardsAmountRequest.strategies', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=151,
)


_L1STAKERREWARDSAMOUNTRESPONSE = _descriptor.Descriptor(
  name='L1StakerRewardsAmountResponse',
  full_name='services.savour_rpc.appchain.L1StakerRewardsAmountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='services.savour_rpc.appchain.L1StakerRewardsAmountResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='services.savour_rpc.appchain.L1StakerRewardsAmountResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='income', full_name='services.savour_rpc.appchain.L1StakerRewardsAmountResponse.income', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=234,
)


_L2STAKERREWARDSAMOUNTREQUEST = _descriptor.Descriptor(
  name='L2StakerRewardsAmountRequest',
  full_name='services.savour_rpc.appchain.L2StakerRewardsAmountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='services.savour_rpc.appchain.L2StakerRewardsAmountRequest.chain_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='staker_address', full_name='services.savour_rpc.appchain.L2StakerRewardsAmountRequest.staker_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='services.savour_rpc.appchain.L2StakerRewardsAmountRequest.strategy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=326,
)


_L2STAKERREWARDSAMOUNTRESPONSE = _descriptor.Descriptor(
  name='L2StakerRewardsAmountResponse',
  full_name='services.savour_rpc.appchain.L2StakerRewardsAmountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='services.savour_rpc.appchain.L2StakerRewardsAmountResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='services.savour_rpc.appchain.L2StakerRewardsAmountResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='income', full_name='services.savour_rpc.appchain.L2StakerRewardsAmountResponse.income', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=409,
)

DESCRIPTOR.message_types_by_name['L1StakerRewardsAmountRequest'] = _L1STAKERREWARDSAMOUNTREQUEST
DESCRIPTOR.message_types_by_name['L1StakerRewardsAmountResponse'] = _L1STAKERREWARDSAMOUNTRESPONSE
DESCRIPTOR.message_types_by_name['L2StakerRewardsAmountRequest'] = _L2STAKERREWARDSAMOUNTREQUEST
DESCRIPTOR.message_types_by_name['L2StakerRewardsAmountResponse'] = _L2STAKERREWARDSAMOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

L1StakerRewardsAmountRequest = _reflection.GeneratedProtocolMessageType('L1StakerRewardsAmountRequest', (_message.Message,), {
  'DESCRIPTOR' : _L1STAKERREWARDSAMOUNTREQUEST,
  '__module__' : 'savour_rpc.appchain_pb2'
  # @@protoc_insertion_point(class_scope:services.savour_rpc.appchain.L1StakerRewardsAmountRequest)
  })
_sym_db.RegisterMessage(L1StakerRewardsAmountRequest)

L1StakerRewardsAmountResponse = _reflection.GeneratedProtocolMessageType('L1StakerRewardsAmountResponse', (_message.Message,), {
  'DESCRIPTOR' : _L1STAKERREWARDSAMOUNTRESPONSE,
  '__module__' : 'savour_rpc.appchain_pb2'
  # @@protoc_insertion_point(class_scope:services.savour_rpc.appchain.L1StakerRewardsAmountResponse)
  })
_sym_db.RegisterMessage(L1StakerRewardsAmountResponse)

L2StakerRewardsAmountRequest = _reflection.GeneratedProtocolMessageType('L2StakerRewardsAmountRequest', (_message.Message,), {
  'DESCRIPTOR' : _L2STAKERREWARDSAMOUNTREQUEST,
  '__module__' : 'savour_rpc.appchain_pb2'
  # @@protoc_insertion_point(class_scope:services.savour_rpc.appchain.L2StakerRewardsAmountRequest)
  })
_sym_db.RegisterMessage(L2StakerRewardsAmountRequest)

L2StakerRewardsAmountResponse = _reflection.GeneratedProtocolMessageType('L2StakerRewardsAmountResponse', (_message.Message,), {
  'DESCRIPTOR' : _L2STAKERREWARDSAMOUNTRESPONSE,
  '__module__' : 'savour_rpc.appchain_pb2'
  # @@protoc_insertion_point(class_scope:services.savour_rpc.appchain.L2StakerRewardsAmountResponse)
  })
_sym_db.RegisterMessage(L2StakerRewardsAmountResponse)


DESCRIPTOR._options = None

_APPCHAINSERVICE = _descriptor.ServiceDescriptor(
  name='AppChainService',
  full_name='services.savour_rpc.appchain.AppChainService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=412,
  serialized_end=723,
  methods=[
  _descriptor.MethodDescriptor(
    name='L1StakerRewardsAmount',
    full_name='services.savour_rpc.appchain.AppChainService.L1StakerRewardsAmount',
    index=0,
    containing_service=None,
    input_type=_L1STAKERREWARDSAMOUNTREQUEST,
    output_type=_L1STAKERREWARDSAMOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='L2StakerRewardsAmount',
    full_name='services.savour_rpc.appchain.AppChainService.L2StakerRewardsAmount',
    index=1,
    containing_service=None,
    input_type=_L2STAKERREWARDSAMOUNTREQUEST,
    output_type=_L2STAKERREWARDSAMOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APPCHAINSERVICE)

DESCRIPTOR.services_by_name['AppChainService'] = _APPCHAINSERVICE

# @@protoc_insertion_point(module_scope)
