# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.savour_rpc import l3staking_pb2 as savour__rpc_dot_l3staking__pb2


class L3StakingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.updateStakingNodeIncome = channel.unary_unary(
                '/services.savour_rpc.l3staking.L3StakingService/updateStakingNodeIncome',
                request_serializer=savour__rpc_dot_l3staking__pb2.StakingNodeReq.SerializeToString,
                response_deserializer=savour__rpc_dot_l3staking__pb2.StakingNodeRep.FromString,
                )


class L3StakingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def updateStakingNodeIncome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_L3StakingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'updateStakingNodeIncome': grpc.unary_unary_rpc_method_handler(
                    servicer.updateStakingNodeIncome,
                    request_deserializer=savour__rpc_dot_l3staking__pb2.StakingNodeReq.FromString,
                    response_serializer=savour__rpc_dot_l3staking__pb2.StakingNodeRep.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.savour_rpc.l3staking.L3StakingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class L3StakingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def updateStakingNodeIncome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/services.savour_rpc.l3staking.L3StakingService/updateStakingNodeIncome',
            savour__rpc_dot_l3staking__pb2.StakingNodeReq.SerializeToString,
            savour__rpc_dot_l3staking__pb2.StakingNodeRep.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
