# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: savour_rpc/l3staking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='savour_rpc/l3staking.proto',
  package='services.savour_rpc.l3staking',
  syntax='proto3',
  serialized_options=b'\n\026group.savour.l3stakingZ\021./proto/l3staking',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asavour_rpc/l3staking.proto\x12\x1dservices.savour_rpc.l3staking\"\x92\x02\n\x0eStakingNodeReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x10\n\x08\x63hain_id\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x12\n\neth_income\x18\x05 \x01(\t\x12\x17\n\x0f\x65th_income_rate\x18\x06 \x01(\t\x12\x11\n\tdp_income\x18\x07 \x01(\t\x12\x16\n\x0e\x64p_income_rate\x18\x08 \x01(\t\x12\x10\n\x08\x65th_evil\x18\t \x01(\t\x12\x15\n\reth_evil_rate\x18\n \x01(\t\x12\x0f\n\x07\x64p_evil\x18\x0b \x01(\t\x12\x14\n\x0c\x64p_evil_rate\x18\x0c \x01(\t\x12\x0b\n\x03tvl\x18\r \x01(\t\"+\n\x0eStakingNodeRep\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x8d\x01\n\x10L3StakingService\x12y\n\x17updateStakingNodeIncome\x12-.services.savour_rpc.l3staking.StakingNodeReq\x1a-.services.savour_rpc.l3staking.StakingNodeRep\"\x00\x42+\n\x16group.savour.l3stakingZ\x11./proto/l3stakingb\x06proto3'
)




_STAKINGNODEREQ = _descriptor.Descriptor(
  name='StakingNodeReq',
  full_name='services.savour_rpc.l3staking.StakingNodeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumer_token', full_name='services.savour_rpc.l3staking.StakingNodeReq.consumer_token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='services.savour_rpc.l3staking.StakingNodeReq.chain_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='services.savour_rpc.l3staking.StakingNodeReq.strategy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='services.savour_rpc.l3staking.StakingNodeReq.address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eth_income', full_name='services.savour_rpc.l3staking.StakingNodeReq.eth_income', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eth_income_rate', full_name='services.savour_rpc.l3staking.StakingNodeReq.eth_income_rate', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp_income', full_name='services.savour_rpc.l3staking.StakingNodeReq.dp_income', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp_income_rate', full_name='services.savour_rpc.l3staking.StakingNodeReq.dp_income_rate', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eth_evil', full_name='services.savour_rpc.l3staking.StakingNodeReq.eth_evil', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eth_evil_rate', full_name='services.savour_rpc.l3staking.StakingNodeReq.eth_evil_rate', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp_evil', full_name='services.savour_rpc.l3staking.StakingNodeReq.dp_evil', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dp_evil_rate', full_name='services.savour_rpc.l3staking.StakingNodeReq.dp_evil_rate', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tvl', full_name='services.savour_rpc.l3staking.StakingNodeReq.tvl', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=336,
)


_STAKINGNODEREP = _descriptor.Descriptor(
  name='StakingNodeRep',
  full_name='services.savour_rpc.l3staking.StakingNodeRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='services.savour_rpc.l3staking.StakingNodeRep.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='services.savour_rpc.l3staking.StakingNodeRep.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=381,
)

DESCRIPTOR.message_types_by_name['StakingNodeReq'] = _STAKINGNODEREQ
DESCRIPTOR.message_types_by_name['StakingNodeRep'] = _STAKINGNODEREP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StakingNodeReq = _reflection.GeneratedProtocolMessageType('StakingNodeReq', (_message.Message,), {
  'DESCRIPTOR' : _STAKINGNODEREQ,
  '__module__' : 'savour_rpc.l3staking_pb2'
  # @@protoc_insertion_point(class_scope:services.savour_rpc.l3staking.StakingNodeReq)
  })
_sym_db.RegisterMessage(StakingNodeReq)

StakingNodeRep = _reflection.GeneratedProtocolMessageType('StakingNodeRep', (_message.Message,), {
  'DESCRIPTOR' : _STAKINGNODEREP,
  '__module__' : 'savour_rpc.l3staking_pb2'
  # @@protoc_insertion_point(class_scope:services.savour_rpc.l3staking.StakingNodeRep)
  })
_sym_db.RegisterMessage(StakingNodeRep)


DESCRIPTOR._options = None

_L3STAKINGSERVICE = _descriptor.ServiceDescriptor(
  name='L3StakingService',
  full_name='services.savour_rpc.l3staking.L3StakingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=384,
  serialized_end=525,
  methods=[
  _descriptor.MethodDescriptor(
    name='updateStakingNodeIncome',
    full_name='services.savour_rpc.l3staking.L3StakingService.updateStakingNodeIncome',
    index=0,
    containing_service=None,
    input_type=_STAKINGNODEREQ,
    output_type=_STAKINGNODEREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_L3STAKINGSERVICE)

DESCRIPTOR.services_by_name['L3StakingService'] = _L3STAKINGSERVICE

# @@protoc_insertion_point(module_scope)
