# Generated by Django 4.1.1 on 2024-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l3staking', '0002_stakingstrategy_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakingstrategy',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='策略地址'),
        ),
    ]
