# Generated by Django 4.1.1 on 2024-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l3staking', '0003_stakingstrategy_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakingchain',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
