# Generated by Django 4.1.1 on 2024-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l3staking', '0004_stakingchain_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='detail',
            field=models.CharField(default='unknown', max_length=500, verbose_name='节点详情'),
        ),
    ]
